# pod.yaml
kind: Pod
apiVersion: v1
metadata:
  name: rails-app
  labels:
    app: rails-app
spec:
  containers:
    - name: rails-app
      image: ideaeclipse/rails-app:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 3000
          name: rails-app
  imagePullSecrets:
    - name: regcred
